name: resfli
description: Restaurant Flui
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_native_splash: ^2.2.9
  flutter_gen: ^4.3.0
  flutter_svg: ^1.1.5
  bordered_text: ^2.0.0
  equatable: ^2.0.5
  dio: ^4.0.6
  alice: ^0.2.5
  pretty_dio_logger: ^1.1.1
  flutter_screenutil: ^5.5.4

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: MaisonNeue-Book
      fonts:
        - asset: assets/fonts/MaisonNeue-Book.otf
    - family: MaisonNeue-Demi
      fonts:
        - asset: assets/fonts/MaisonNeue-Demi.otf
    - family: MaisonNeue-Bold
      fonts:
        - asset: assets/fonts/MaisonNeue-Bold.otf

flutter_gen:
  integrations:
    flutter_svg: true
